baseURL = "https://casamento-luciana.vercel.app"
theme = "nostyle"
relativeURLs = true
title = "Casamento Luciana e Kaio"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
removePathAccents = true
enableInlineShortcodes = true

[menu]

[[menu.main]]
    name = "Início"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Lista de Presentes"
    url = "#presentes"
    weight = 10

[[menu.main]]
    name = "Sobre nós"
    url = "/about/"
    weight = 20

[[menu.main]]
    name = "Contato"
    url = "#contact"
    weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
  custom_css = [
    "css/base", 
    "css/menu",
    "css/hero",
    "/css/info",
    "/css/suggest",
    "/css/forms",
    "/css/dialog",
    "css/history"]

  custom_js = [
    "/js/custom",
    "/js/menu",
    "/js/email"]

  show_description = true
  slogan = "Um espaço de Criação e Inspiração"
  description = "Acreditamos que a papelaria pode ir além do funcional, e por isso, cada produto Purpry Papers é pensado para encantar e surpreender."
  favicon = "/icons/favicon.png"
  appleIcon = "/icons/apple-icon.png"
  logotipo = "/images/logotipo.svg"
  
[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
